name: flutter_exploring
description: "In this Project, I will be exploring flutter widget's from various packages and also learn, bloc pattern, dependency injection and others."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  cli_completion: ^0.5.1
  equatable: ^2.0.5
  path_provider: ^2.1.4

  hydrated_bloc_testground:
    path: packages/hydrated_bloc_testground

  storage:
    path: packages/storage/storage
  secure_storage:
    path: packages/storage/secure_storage
  persistent_storage:
    path: packages/storage/persistent_storage
  flutter_secure_storage:
  shared_preferences:
  form_inputs:
    path: packages/form_inputs
  flutter_svg:
  intl:
  intl_utils:
  get_it: ^8.0.1
  gap: ^3.0.1
  fpdart: ^1.1.0
  skeletonizer: ^1.4.2
  shimmer: ^3.0.0
  go_router: ^14.3.0
  flutter_spinkit: ^5.2.1
  hydrated_bloc: ^9.1.5
  rxdart: ^0.28.0
  flutter_hooks: ^0.20.5
  supabase_flutter:

  dio:
  dartz:
  flutter_gemini: ^2.0.5
  flutter_dotenv: ^5.2.1
  markdown: ^7.2.2
  flutter_markdown: ^0.7.4+2



dev_dependencies:

  flutter_test:
    sdk: flutter
  test: ^1.16.0
  flutter_lints: ^5.0.0
  melos: ^6.2.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  monarch: ^3.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - .env
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
